window.MOCK = {
  "asOf": "2026-09-15",
  "customers": [
    {
      "Customer_ID": "CUST-0001",
      "Customer_Name": "คุณลูกค้า 1",
      "Phone_Number": "0861-960-6390",
      "Car_Brand": "Toyota",
      "Car_Model": "Corolla Altis",
      "Car_Year": "2020",
      "Current_Insurer": "บริษัท C (Thai Auto)",
      "Current_Policy_Type": "ชั้น 2+",
      "Current_Premium_THB": "฿10,592",
      "Policy_Expiry_Date": "2026-09-20",
      "Days_To_Expiry": "5",
      "Contact_Status": "ยังไม่ได้ติดต่อ",
      "Historical_Renewal_Behavior": "ชอบเปลี่ยนบริษัทประกันเพื่อราคา",
      "premium": 10592,
      "daysToExpiryRaw": 5,
      "carYear": 2020
    },
    {
      "Customer_ID": "CUST-0002",
      "Customer_Name": "คุณลูกค้า 2",
      "Phone_Number": "0884-187-9322",
      "Car_Brand": "Toyota",
      "Car_Model": "Yaris Ativ",
      "Car_Year": "2022",
      "Current_Insurer": "บริษัท E (Eco Guard)",
      "Current_Policy_Type": "ชั้น 3+",
      "Current_Premium_THB": "฿9,933",
      "Policy_Expiry_Date": "2026-09-20",
      "Days_To_Expiry": "5",
      "Contact_Status": "ยังไม่ได้ติดต่อ",
      "Historical_Renewal_Behavior": "เคยมีประวัติเคลมหนัก",
      "premium": 9933,
      "daysToExpiryRaw": 5,
      "carYear": 2022
    },
    {
      "Customer_ID": "CUST-0003",
      "Customer_Name": "คุณลูกค้า 3",
      "Phone_Number": "0867-121-7396",
      "Car_Brand": "Toyota",
      "Car_Model": "Fortuner",
      "Car_Year": "2019",
      "Current_Insurer": "บริษัท D (Premium Care)",
      "Current_Policy_Type": "ชั้น 1",
      "Current_Premium_THB": "฿23,666",
      "Policy_Expiry_Date": "2026-09-29",
      "Days_To_Expiry": "14",
      "Contact_Status": "ยังไม่ได้ติดต่อ",
      "Historical_Renewal_Behavior": "เคยมีประวัติเคลมหนัก",
      "premium": 23666,
      "daysToExpiryRaw": 14,
      "carYear": 2019
    },
    {
      "Customer_ID": "CUST-0004",
      "Customer_Name": "คุณลูกค้า 4",
      "Phone_Number": "0869-882-1189",
      "Car_Brand": "Toyota",
      "Car_Model": "Hilux Revo",
      "Car_Year": "2021",
      "Current_Insurer": "บริษัท C (Thai Auto)",
      "Current_Policy_Type": "ชั้น 1",
      "Current_Premium_THB": "฿16,267",
      "Policy_Expiry_Date": "2026-09-25",
      "Days_To_Expiry": "10",
      "Contact_Status": "ยังไม่ได้ติดต่อ",
      "Historical_Renewal_Behavior": "ชอบเปลี่ยนบริษัทประกันเพื่อราคา",
      "premium": 16267,
      "daysToExpiryRaw": 10,
      "carYear": 2021
    },
    {
      "Customer_ID": "CUST-0005",
      "Customer_Name": "คุณลูกค้า 5",
      "Phone_Number": "0816-120-6393",
      "Car_Brand": "Honda",
      "Car_Model": "Civic",
      "Car_Year": "2020",
      "Current_Insurer": "บริษัท D (Premium Care)",
      "Current_Policy_Type": "ชั้น 3+",
      "Current_Premium_THB": "฿9,561",
      "Policy_Expiry_Date": "2026-10-06",
      "Days_To_Expiry": "21",
      "Contact_Status": "ยังไม่ได้ติดต่อ",
      "Historical_Renewal_Behavior": "ต่ออายุตรงเวลาเสมอ",
      "premium": 9561,
      "daysToExpiryRaw": 21,
      "carYear": 2020
    },
    {
      "Customer_ID": "CUST-0006",
      "Customer_Name": "คุณลูกค้า 6",
      "Phone_Number": "0811-439-7235",
      "Car_Brand": "Honda",
      "Car_Model": "City",
      "Car_Year": "2021",
      "Current_Insurer": "บริษัท D (Premium Care)",
      "Current_Policy_Type": "ชั้น 1",
      "Current_Premium_THB": "฿15,775",
      "Policy_Expiry_Date": "2026-09-18",
      "Days_To_Expiry": "3",
      "Contact_Status": "ติดต่อแล้ว-ปฏิเสธ",
      "Historical_Renewal_Behavior": "เคยมีประวัติเคลมหนัก",
      "premium": 15775,
      "daysToExpiryRaw": 3,
      "carYear": 2021
    },
    {
      "Customer_ID": "CUST-0007",
      "Customer_Name": "คุณลูกค้า 7",
      "Phone_Number": "0859-971-8555",
      "Car_Brand": "Honda",
      "Car_Model": "CR-V",
      "Car_Year": "2019",
      "Current_Insurer": "บริษัท B (Safety Plus)",
      "Current_Policy_Type": "ชั้น 1",
      "Current_Premium_THB": "฿18,843",
      "Policy_Expiry_Date": "2026-09-20",
      "Days_To_Expiry": "5",
      "Contact_Status": "ติดต่อแล้ว-ปฏิเสธ",
      "Historical_Renewal_Behavior": "ต่ออายุเฉียดฉิว",
      "premium": 18843,
      "daysToExpiryRaw": 5,
      "carYear": 2019
    },
    {
      "Customer_ID": "CUST-0008",
      "Customer_Name": "คุณลูกค้า 8",
      "Phone_Number": "0853-261-5297",
      "Car_Brand": "Honda",
      "Car_Model": "HR-V",
      "Car_Year": "2022",
      "Current_Insurer": "บริษัท D (Premium Care)",
      "Current_Policy_Type": "ชั้น 1",
      "Current_Premium_THB": "฿22,629",
      "Policy_Expiry_Date": "2026-09-20",
      "Days_To_Expiry": "5",
      "Contact_Status": "ยังไม่ได้ติดต่อ",
      "Historical_Renewal_Behavior": "เคยมีประวัติเคลมหนัก",
      "premium": 22629,
      "daysToExpiryRaw": 5,
      "carYear": 2022
    },
    {
      "Customer_ID": "CUST-0009",
      "Customer_Name": "คุณลูกค้า 9",
      "Phone_Number": "0894-819-8916",
      "Car_Brand": "Mazda",
      "Car_Model": "CX-5",
      "Car_Year": "2018",
      "Current_Insurer": "บริษัท B (Safety Plus)",
      "Current_Policy_Type": "ชั้น 1",
      "Current_Premium_THB": "฿19,887",
      "Policy_Expiry_Date": "2026-09-22",
      "Days_To_Expiry": "7",
      "Contact_Status": "ยังไม่ได้ติดต่อ",
      "Historical_Renewal_Behavior": "เคยมีประวัติเคลมหนัก",
      "premium": 19887,
      "daysToExpiryRaw": 7,
      "carYear": 2018
    },
    {
      "Customer_ID": "CUST-0010",
      "Customer_Name": "คุณลูกค้า 10",
      "Phone_Number": "0850-256-3062",
      "Car_Brand": "Mazda",
      "Car_Model": "Mazda 3",
      "Car_Year": "2020",
      "Current_Insurer": "บริษัท E (Eco Guard)",
      "Current_Policy_Type": "ชั้น 1",
      "Current_Premium_THB": "฿23,006",
      "Policy_Expiry_Date": "2026-09-22",
      "Days_To_Expiry": "7",
      "Contact_Status": "ยังไม่ได้ติดต่อ",
      "Historical_Renewal_Behavior": "เคยมีประวัติเคลมหนัก",
      "premium": 23006,
      "daysToExpiryRaw": 7,
      "carYear": 2020
    },
    {
      "Customer_ID": "CUST-0011",
      "Customer_Name": "คุณลูกค้า 11",
      "Phone_Number": "0897-162-6258",
      "Car_Brand": "Mazda",
      "Car_Model": "CX-30",
      "Car_Year": "2021",
      "Current_Insurer": "บริษัท C (Thai Auto)",
      "Current_Policy_Type": "ชั้น 2+",
      "Current_Premium_THB": "฿12,014",
      "Policy_Expiry_Date": "2026-10-06",
      "Days_To_Expiry": "21",
      "Contact_Status": "ยังไม่ได้ติดต่อ",
      "Historical_Renewal_Behavior": "ชอบเปลี่ยนบริษัทประกันเพื่อราคา",
      "premium": 12014,
      "daysToExpiryRaw": 21,
      "carYear": 2021
    },
    {
      "Customer_ID": "CUST-0012",
      "Customer_Name": "คุณลูกค้า 12",
      "Phone_Number": "0850-127-7278",
      "Car_Brand": "Isuzu",
      "Car_Model": "D-Max",
      "Car_Year": "2020",
      "Current_Insurer": "บริษัท A (ANC Shield)",
      "Current_Policy_Type": "ชั้น 2+",
      "Current_Premium_THB": "฿10,604",
      "Policy_Expiry_Date": "2026-09-18",
      "Days_To_Expiry": "3",
      "Contact_Status": "ยังไม่ได้ติดต่อ",
      "Historical_Renewal_Behavior": "เคยมีประวัติเคลมหนัก",
      "premium": 10604,
      "daysToExpiryRaw": 3,
      "carYear": 2020
    },
    {
      "Customer_ID": "CUST-0013",
      "Customer_Name": "คุณลูกค้า 13",
      "Phone_Number": "0846-198-3731",
      "Car_Brand": "Isuzu",
      "Car_Model": "Mu-X",
      "Car_Year": "2019",
      "Current_Insurer": "บริษัท C (Thai Auto)",
      "Current_Policy_Type": "ชั้น 1",
      "Current_Premium_THB": "฿23,110",
      "Policy_Expiry_Date": "2026-09-29",
      "Days_To_Expiry": "14",
      "Contact_Status": "ติดต่อแล้ว-ขอส่วนลด",
      "Historical_Renewal_Behavior": "ต่ออายุเฉียดฉิว",
      "premium": 23110,
      "daysToExpiryRaw": 14,
      "carYear": 2019
    },
    {
      "Customer_ID": "CUST-0014",
      "Customer_Name": "คุณลูกค้า 14",
      "Phone_Number": "0823-970-7938",
      "Car_Brand": "Nissan",
      "Car_Model": "Almera",
      "Car_Year": "2021",
      "Current_Insurer": "บริษัท A (ANC Shield)",
      "Current_Policy_Type": "ชั้น 2+",
      "Current_Premium_THB": "฿8,984",
      "Policy_Expiry_Date": "2026-09-20",
      "Days_To_Expiry": "5",
      "Contact_Status": "ติดต่อแล้ว-ลังเล",
      "Historical_Renewal_Behavior": "ต่ออายุตรงเวลาเสมอ",
      "premium": 8984,
      "daysToExpiryRaw": 5,
      "carYear": 2021
    },
    {
      "Customer_ID": "CUST-0015",
      "Customer_Name": "คุณลูกค้า 15",
      "Phone_Number": "0861-195-7019",
      "Car_Brand": "Nissan",
      "Car_Model": "Kicks",
      "Car_Year": "2022",
      "Current_Insurer": "บริษัท E (Eco Guard)",
      "Current_Policy_Type": "ชั้น 1",
      "Current_Premium_THB": "฿21,892",
      "Policy_Expiry_Date": "2026-09-25",
      "Days_To_Expiry": "10",
      "Contact_Status": "ยังไม่ได้ติดต่อ",
      "Historical_Renewal_Behavior": "ต่ออายุตรงเวลาเสมอ",
      "premium": 21892,
      "daysToExpiryRaw": 10,
      "carYear": 2022
    },
    {
      "Customer_ID": "CUST-0016",
      "Customer_Name": "คุณลูกค้า 16",
      "Phone_Number": "0841-938-4157",
      "Car_Brand": "MG",
      "Car_Model": "ZS",
      "Car_Year": "2021",
      "Current_Insurer": "บริษัท D (Premium Care)",
      "Current_Policy_Type": "ชั้น 3+",
      "Current_Premium_THB": "฿9,097",
      "Policy_Expiry_Date": "2026-09-29",
      "Days_To_Expiry": "14",
      "Contact_Status": "ติดต่อแล้ว-ลังเล",
      "Historical_Renewal_Behavior": "เคยมีประวัติเคลมหนัก",
      "premium": 9097,
      "daysToExpiryRaw": 14,
      "carYear": 2021
    },
    {
      "Customer_ID": "CUST-0017",
      "Customer_Name": "คุณลูกค้า 17",
      "Phone_Number": "0853-439-6450",
      "Car_Brand": "MG",
      "Car_Model": "4 EV",
      "Car_Year": "2023",
      "Current_Insurer": "บริษัท B (Safety Plus)",
      "Current_Policy_Type": "ชั้น 1",
      "Current_Premium_THB": "฿20,592",
      "Policy_Expiry_Date": "2026-09-22",
      "Days_To_Expiry": "7",
      "Contact_Status": "ยังไม่ได้ติดต่อ",
      "Historical_Renewal_Behavior": "ต่ออายุตรงเวลาเสมอ",
      "premium": 20592,
      "daysToExpiryRaw": 7,
      "carYear": 2023
    },
    {
      "Customer_ID": "CUST-0018",
      "Customer_Name": "คุณลูกค้า 18",
      "Phone_Number": "0836-732-6864",
      "Car_Brand": "BYD",
      "Car_Model": "Atto 3",
      "Car_Year": "2023",
      "Current_Insurer": "บริษัท C (Thai Auto)",
      "Current_Policy_Type": "ชั้น 1",
      "Current_Premium_THB": "฿20,575",
      "Policy_Expiry_Date": "2026-09-25",
      "Days_To_Expiry": "10",
      "Contact_Status": "ติดต่อแล้ว-สนใจเปรียบเทียบ",
      "Historical_Renewal_Behavior": "ต่ออายุตรงเวลาเสมอ",
      "premium": 20575,
      "daysToExpiryRaw": 10,
      "carYear": 2023
    },
    {
      "Customer_ID": "CUST-0019",
      "Customer_Name": "คุณลูกค้า 19",
      "Phone_Number": "0860-333-1663",
      "Car_Brand": "BYD",
      "Car_Model": "Dolphin",
      "Car_Year": "2023",
      "Current_Insurer": "บริษัท C (Thai Auto)",
      "Current_Policy_Type": "ชั้น 1",
      "Current_Premium_THB": "฿16,495",
      "Policy_Expiry_Date": "2026-09-29",
      "Days_To_Expiry": "14",
      "Contact_Status": "ยังไม่ได้ติดต่อ",
      "Historical_Renewal_Behavior": "ต่ออายุตรงเวลาเสมอ",
      "premium": 16495,
      "daysToExpiryRaw": 14,
      "carYear": 2023
    },
    {
      "Customer_ID": "CUST-0020",
      "Customer_Name": "คุณลูกค้า 20",
      "Phone_Number": "0867-663-2291",
      "Car_Brand": "BMW",
      "Car_Model": "330e",
      "Car_Year": "2021",
      "Current_Insurer": "บริษัท B (Safety Plus)",
      "Current_Policy_Type": "ชั้น 2+",
      "Current_Premium_THB": "฿29,636",
      "Policy_Expiry_Date": "2026-09-22",
      "Days_To_Expiry": "7",
      "Contact_Status": "ยังไม่ได้ติดต่อ",
      "Historical_Renewal_Behavior": "ต่ออายุตรงเวลาเสมอ",
      "premium": 29636,
      "daysToExpiryRaw": 7,
      "carYear": 2021
    },
    {
      "Customer_ID": "CUST-0021",
      "Customer_Name": "คุณลูกค้า 21",
      "Phone_Number": "0811-741-1854",
      "Car_Brand": "BMW",
      "Car_Model": "X3",
      "Car_Year": "2020",
      "Current_Insurer": "บริษัท E (Eco Guard)",
      "Current_Policy_Type": "ชั้น 1",
      "Current_Premium_THB": "฿41,949",
      "Policy_Expiry_Date": "2026-09-20",
      "Days_To_Expiry": "5",
      "Contact_Status": "ติดต่อแล้ว-สนใจเปรียบเทียบ",
      "Historical_Renewal_Behavior": "เคยมีประวัติเคลมหนัก",
      "premium": 41949,
      "daysToExpiryRaw": 5,
      "carYear": 2020
    },
    {
      "Customer_ID": "CUST-0022",
      "Customer_Name": "คุณลูกค้า 22",
      "Phone_Number": "0879-515-5931",
      "Car_Brand": "Mercedes-Benz",
      "Car_Model": "C220d",
      "Car_Year": "2020",
      "Current_Insurer": "บริษัท C (Thai Auto)",
      "Current_Policy_Type": "ชั้น 1",
      "Current_Premium_THB": "฿40,688",
      "Policy_Expiry_Date": "2026-09-29",
      "Days_To_Expiry": "14",
      "Contact_Status": "ยังไม่ได้ติดต่อ",
      "Historical_Renewal_Behavior": "เคยมีประวัติเคลมหนัก",
      "premium": 40688,
      "daysToExpiryRaw": 14,
      "carYear": 2020
    },
    {
      "Customer_ID": "CUST-0023",
      "Customer_Name": "คุณลูกค้า 23",
      "Phone_Number": "0879-610-7287",
      "Car_Brand": "Mercedes-Benz",
      "Car_Model": "E300e",
      "Car_Year": "2019",
      "Current_Insurer": "บริษัท A (ANC Shield)",
      "Current_Policy_Type": "ชั้น 1",
      "Current_Premium_THB": "฿39,589",
      "Policy_Expiry_Date": "2026-09-29",
      "Days_To_Expiry": "14",
      "Contact_Status": "ติดต่อแล้ว-ลังเล",
      "Historical_Renewal_Behavior": "เคยมีประวัติเคลมหนัก",
      "premium": 39589,
      "daysToExpiryRaw": 14,
      "carYear": 2019
    },
    {
      "Customer_ID": "CUST-0024",
      "Customer_Name": "คุณลูกค้า 24",
      "Phone_Number": "0868-502-2986",
      "Car_Brand": "Tesla",
      "Car_Model": "Model 3",
      "Car_Year": "2023",
      "Current_Insurer": "บริษัท C (Thai Auto)",
      "Current_Policy_Type": "ชั้น 1",
      "Current_Premium_THB": "฿29,734",
      "Policy_Expiry_Date": "2026-09-20",
      "Days_To_Expiry": "5",
      "Contact_Status": "ติดต่อแล้ว-ขอส่วนลด",
      "Historical_Renewal_Behavior": "เคยมีประวัติเคลมหนัก",
      "premium": 29734,
      "daysToExpiryRaw": 5,
      "carYear": 2023
    },
    {
      "Customer_ID": "CUST-0025",
      "Customer_Name": "คุณลูกค้า 25",
      "Phone_Number": "0848-437-5736",
      "Car_Brand": "Tesla",
      "Car_Model": "Model Y",
      "Car_Year": "2023",
      "Current_Insurer": "บริษัท C (Thai Auto)",
      "Current_Policy_Type": "ชั้น 1",
      "Current_Premium_THB": "฿34,616",
      "Policy_Expiry_Date": "2026-09-20",
      "Days_To_Expiry": "5",
      "Contact_Status": "ติดต่อแล้ว-สนใจเปรียบเทียบ",
      "Historical_Renewal_Behavior": "ต่ออายุเฉียดฉิว",
      "premium": 34616,
      "daysToExpiryRaw": 5,
      "carYear": 2023
    },
    {
      "Customer_ID": "CUST-0026",
      "Customer_Name": "คุณลูกค้า 26",
      "Phone_Number": "0816-863-7287",
      "Car_Brand": "Toyota",
      "Car_Model": "Camry",
      "Car_Year": "2018",
      "Current_Insurer": "บริษัท B (Safety Plus)",
      "Current_Policy_Type": "ชั้น 3+",
      "Current_Premium_THB": "฿11,143",
      "Policy_Expiry_Date": "2026-09-22",
      "Days_To_Expiry": "7",
      "Contact_Status": "ติดต่อแล้ว-ปฏิเสธ",
      "Historical_Renewal_Behavior": "ต่ออายุเฉียดฉิว",
      "premium": 11143,
      "daysToExpiryRaw": 7,
      "carYear": 2018
    },
    {
      "Customer_ID": "CUST-0027",
      "Customer_Name": "คุณลูกค้า 27",
      "Phone_Number": "0821-552-4108",
      "Car_Brand": "Toyota",
      "Car_Model": "Corolla Altis",
      "Car_Year": "2020",
      "Current_Insurer": "บริษัท C (Thai Auto)",
      "Current_Policy_Type": "ชั้น 1",
      "Current_Premium_THB": "฿22,400",
      "Policy_Expiry_Date": "2026-09-22",
      "Days_To_Expiry": "7",
      "Contact_Status": "ติดต่อแล้ว-ขอส่วนลด",
      "Historical_Renewal_Behavior": "ชอบเปลี่ยนบริษัทประกันเพื่อราคา",
      "premium": 22400,
      "daysToExpiryRaw": 7,
      "carYear": 2020
    },
    {
      "Customer_ID": "CUST-0028",
      "Customer_Name": "คุณลูกค้า 28",
      "Phone_Number": "0829-251-7197",
      "Car_Brand": "Toyota",
      "Car_Model": "Yaris Ativ",
      "Car_Year": "2022",
      "Current_Insurer": "บริษัท A (ANC Shield)",
      "Current_Policy_Type": "ชั้น 2+",
      "Current_Premium_THB": "฿12,182",
      "Policy_Expiry_Date": "2026-10-30",
      "Days_To_Expiry": "45",
      "Contact_Status": "ติดต่อแล้ว-ขอส่วนลด",
      "Historical_Renewal_Behavior": "เคยมีประวัติเคลมหนัก",
      "premium": 12182,
      "daysToExpiryRaw": 45,
      "carYear": 2022
    },
    {
      "Customer_ID": "CUST-0029",
      "Customer_Name": "คุณลูกค้า 29",
      "Phone_Number": "0893-353-3557",
      "Car_Brand": "Toyota",
      "Car_Model": "Fortuner",
      "Car_Year": "2019",
      "Current_Insurer": "บริษัท A (ANC Shield)",
      "Current_Policy_Type": "ชั้น 2+",
      "Current_Premium_THB": "฿10,461",
      "Policy_Expiry_Date": "2026-09-20",
      "Days_To_Expiry": "5",
      "Contact_Status": "ติดต่อแล้ว-สนใจเปรียบเทียบ",
      "Historical_Renewal_Behavior": "ต่ออายุเฉียดฉิว",
      "premium": 10461,
      "daysToExpiryRaw": 5,
      "carYear": 2019
    },
    {
      "Customer_ID": "CUST-0030",
      "Customer_Name": "คุณลูกค้า 30",
      "Phone_Number": "0844-819-1956",
      "Car_Brand": "Toyota",
      "Car_Model": "Hilux Revo",
      "Car_Year": "2021",
      "Current_Insurer": "บริษัท A (ANC Shield)",
      "Current_Policy_Type": "ชั้น 1",
      "Current_Premium_THB": "฿20,699",
      "Policy_Expiry_Date": "2026-09-20",
      "Days_To_Expiry": "5",
      "Contact_Status": "ยังไม่ได้ติดต่อ",
      "Historical_Renewal_Behavior": "เคยมีประวัติเคลมหนัก",
      "premium": 20699,
      "daysToExpiryRaw": 5,
      "carYear": 2021
    },
    {
      "Customer_ID": "CUST-0031",
      "Customer_Name": "คุณลูกค้า 31",
      "Phone_Number": "0817-234-2218",
      "Car_Brand": "Honda",
      "Car_Model": "Civic",
      "Car_Year": "2020",
      "Current_Insurer": "บริษัท A (ANC Shield)",
      "Current_Policy_Type": "ชั้น 1",
      "Current_Premium_THB": "฿19,555",
      "Policy_Expiry_Date": "2026-09-25",
      "Days_To_Expiry": "10",
      "Contact_Status": "ติดต่อแล้ว-สนใจเปรียบเทียบ",
      "Historical_Renewal_Behavior": "ต่ออายุเฉียดฉิว",
      "premium": 19555,
      "daysToExpiryRaw": 10,
      "carYear": 2020
    },
    {
      "Customer_ID": "CUST-0032",
      "Customer_Name": "คุณลูกค้า 32",
      "Phone_Number": "0839-137-4436",
      "Car_Brand": "Honda",
      "Car_Model": "City",
      "Car_Year": "2021",
      "Current_Insurer": "บริษัท C (Thai Auto)",
      "Current_Policy_Type": "ชั้น 2+",
      "Current_Premium_THB": "฿10,854",
      "Policy_Expiry_Date": "2026-09-22",
      "Days_To_Expiry": "7",
      "Contact_Status": "ยังไม่ได้ติดต่อ",
      "Historical_Renewal_Behavior": "ต่ออายุตรงเวลาเสมอ",
      "premium": 10854,
      "daysToExpiryRaw": 7,
      "carYear": 2021
    },
    {
      "Customer_ID": "CUST-0033",
      "Customer_Name": "คุณลูกค้า 33",
      "Phone_Number": "0837-978-6600",
      "Car_Brand": "Honda",
      "Car_Model": "CR-V",
      "Car_Year": "2019",
      "Current_Insurer": "บริษัท E (Eco Guard)",
      "Current_Policy_Type": "ชั้น 1",
      "Current_Premium_THB": "฿22,683",
      "Policy_Expiry_Date": "2026-09-18",
      "Days_To_Expiry": "3",
      "Contact_Status": "ติดต่อแล้ว-สนใจเปรียบเทียบ",
      "Historical_Renewal_Behavior": "ต่ออายุตรงเวลาเสมอ",
      "premium": 22683,
      "daysToExpiryRaw": 3,
      "carYear": 2019
    },
    {
      "Customer_ID": "CUST-0034",
      "Customer_Name": "คุณลูกค้า 34",
      "Phone_Number": "0853-319-3205",
      "Car_Brand": "Honda",
      "Car_Model": "HR-V",
      "Car_Year": "2022",
      "Current_Insurer": "บริษัท E (Eco Guard)",
      "Current_Policy_Type": "ชั้น 1",
      "Current_Premium_THB": "฿16,060",
      "Policy_Expiry_Date": "2026-10-15",
      "Days_To_Expiry": "30",
      "Contact_Status": "ติดต่อแล้ว-สนใจเปรียบเทียบ",
      "Historical_Renewal_Behavior": "ต่ออายุตรงเวลาเสมอ",
      "premium": 16060,
      "daysToExpiryRaw": 30,
      "carYear": 2022
    },
    {
      "Customer_ID": "CUST-0035",
      "Customer_Name": "คุณลูกค้า 35",
      "Phone_Number": "0869-215-1190",
      "Car_Brand": "Mazda",
      "Car_Model": "CX-5",
      "Car_Year": "2018",
      "Current_Insurer": "บริษัท E (Eco Guard)",
      "Current_Policy_Type": "ชั้น 1",
      "Current_Premium_THB": "฿21,102",
      "Policy_Expiry_Date": "2026-09-22",
      "Days_To_Expiry": "7",
      "Contact_Status": "ติดต่อแล้ว-สนใจเปรียบเทียบ",
      "Historical_Renewal_Behavior": "ต่ออายุเฉียดฉิว",
      "premium": 21102,
      "daysToExpiryRaw": 7,
      "carYear": 2018
    },
    {
      "Customer_ID": "CUST-0036",
      "Customer_Name": "คุณลูกค้า 36",
      "Phone_Number": "0834-834-7709",
      "Car_Brand": "Mazda",
      "Car_Model": "Mazda 3",
      "Car_Year": "2020",
      "Current_Insurer": "บริษัท B (Safety Plus)",
      "Current_Policy_Type": "ชั้น 3+",
      "Current_Premium_THB": "฿10,233",
      "Policy_Expiry_Date": "2026-09-18",
      "Days_To_Expiry": "3",
      "Contact_Status": "ติดต่อแล้ว-สนใจเปรียบเทียบ",
      "Historical_Renewal_Behavior": "ต่ออายุเฉียดฉิว",
      "premium": 10233,
      "daysToExpiryRaw": 3,
      "carYear": 2020
    },
    {
      "Customer_ID": "CUST-0037",
      "Customer_Name": "คุณลูกค้า 37",
      "Phone_Number": "0832-738-1154",
      "Car_Brand": "Mazda",
      "Car_Model": "CX-30",
      "Car_Year": "2021",
      "Current_Insurer": "บริษัท B (Safety Plus)",
      "Current_Policy_Type": "ชั้น 2+",
      "Current_Premium_THB": "฿8,284",
      "Policy_Expiry_Date": "2026-10-06",
      "Days_To_Expiry": "21",
      "Contact_Status": "ยังไม่ได้ติดต่อ",
      "Historical_Renewal_Behavior": "ต่ออายุเฉียดฉิว",
      "premium": 8284,
      "daysToExpiryRaw": 21,
      "carYear": 2021
    },
    {
      "Customer_ID": "CUST-0038",
      "Customer_Name": "คุณลูกค้า 38",
      "Phone_Number": "0857-138-6596",
      "Car_Brand": "Isuzu",
      "Car_Model": "D-Max",
      "Car_Year": "2020",
      "Current_Insurer": "บริษัท B (Safety Plus)",
      "Current_Policy_Type": "ชั้น 2+",
      "Current_Premium_THB": "฿9,341",
      "Policy_Expiry_Date": "2026-10-15",
      "Days_To_Expiry": "30",
      "Contact_Status": "ติดต่อแล้ว-ปฏิเสธ",
      "Historical_Renewal_Behavior": "ต่ออายุเฉียดฉิว",
      "premium": 9341,
      "daysToExpiryRaw": 30,
      "carYear": 2020
    },
    {
      "Customer_ID": "CUST-0039",
      "Customer_Name": "คุณลูกค้า 39",
      "Phone_Number": "0816-924-5780",
      "Car_Brand": "Isuzu",
      "Car_Model": "Mu-X",
      "Car_Year": "2019",
      "Current_Insurer": "บริษัท D (Premium Care)",
      "Current_Policy_Type": "ชั้น 2+",
      "Current_Premium_THB": "฿11,995",
      "Policy_Expiry_Date": "2026-09-18",
      "Days_To_Expiry": "3",
      "Contact_Status": "ติดต่อแล้ว-ลังเล",
      "Historical_Renewal_Behavior": "ชอบเปลี่ยนบริษัทประกันเพื่อราคา",
      "premium": 11995,
      "daysToExpiryRaw": 3,
      "carYear": 2019
    },
    {
      "Customer_ID": "CUST-0040",
      "Customer_Name": "คุณลูกค้า 40",
      "Phone_Number": "0875-899-1853",
      "Car_Brand": "Nissan",
      "Car_Model": "Almera",
      "Car_Year": "2021",
      "Current_Insurer": "บริษัท C (Thai Auto)",
      "Current_Policy_Type": "ชั้น 1",
      "Current_Premium_THB": "฿15,574",
      "Policy_Expiry_Date": "2026-11-14",
      "Days_To_Expiry": "60",
      "Contact_Status": "ติดต่อแล้ว-ลังเล",
      "Historical_Renewal_Behavior": "ต่ออายุเฉียดฉิว",
      "premium": 15574,
      "daysToExpiryRaw": 60,
      "carYear": 2021
    },
    {
      "Customer_ID": "CUST-0041",
      "Customer_Name": "คุณลูกค้า 41",
      "Phone_Number": "0895-404-5777",
      "Car_Brand": "Nissan",
      "Car_Model": "Kicks",
      "Car_Year": "2022",
      "Current_Insurer": "บริษัท C (Thai Auto)",
      "Current_Policy_Type": "ชั้น 1",
      "Current_Premium_THB": "฿18,124",
      "Policy_Expiry_Date": "2026-09-22",
      "Days_To_Expiry": "7",
      "Contact_Status": "ติดต่อแล้ว-ปฏิเสธ",
      "Historical_Renewal_Behavior": "ชอบเปลี่ยนบริษัทประกันเพื่อราคา",
      "premium": 18124,
      "daysToExpiryRaw": 7,
      "carYear": 2022
    },
    {
      "Customer_ID": "CUST-0042",
      "Customer_Name": "คุณลูกค้า 42",
      "Phone_Number": "0877-873-1876",
      "Car_Brand": "MG",
      "Car_Model": "ZS",
      "Car_Year": "2021",
      "Current_Insurer": "บริษัท D (Premium Care)",
      "Current_Policy_Type": "ชั้น 1",
      "Current_Premium_THB": "฿21,966",
      "Policy_Expiry_Date": "2026-09-20",
      "Days_To_Expiry": "5",
      "Contact_Status": "ยังไม่ได้ติดต่อ",
      "Historical_Renewal_Behavior": "ต่ออายุเฉียดฉิว",
      "premium": 21966,
      "daysToExpiryRaw": 5,
      "carYear": 2021
    },
    {
      "Customer_ID": "CUST-0043",
      "Customer_Name": "คุณลูกค้า 43",
      "Phone_Number": "0839-758-5752",
      "Car_Brand": "MG",
      "Car_Model": "4 EV",
      "Car_Year": "2023",
      "Current_Insurer": "บริษัท C (Thai Auto)",
      "Current_Policy_Type": "ชั้น 1",
      "Current_Premium_THB": "฿23,932",
      "Policy_Expiry_Date": "2026-09-20",
      "Days_To_Expiry": "5",
      "Contact_Status": "ยังไม่ได้ติดต่อ",
      "Historical_Renewal_Behavior": "ชอบเปลี่ยนบริษัทประกันเพื่อราคา",
      "premium": 23932,
      "daysToExpiryRaw": 5,
      "carYear": 2023
    },
    {
      "Customer_ID": "CUST-0044",
      "Customer_Name": "คุณลูกค้า 44",
      "Phone_Number": "0818-740-2081",
      "Car_Brand": "BYD",
      "Car_Model": "Atto 3",
      "Car_Year": "2023",
      "Current_Insurer": "บริษัท B (Safety Plus)",
      "Current_Policy_Type": "ชั้น 1",
      "Current_Premium_THB": "฿22,805",
      "Policy_Expiry_Date": "2026-09-18",
      "Days_To_Expiry": "3",
      "Contact_Status": "ยังไม่ได้ติดต่อ",
      "Historical_Renewal_Behavior": "ต่ออายุตรงเวลาเสมอ",
      "premium": 22805,
      "daysToExpiryRaw": 3,
      "carYear": 2023
    },
    {
      "Customer_ID": "CUST-0045",
      "Customer_Name": "คุณลูกค้า 45",
      "Phone_Number": "0810-371-5070",
      "Car_Brand": "BYD",
      "Car_Model": "Dolphin",
      "Car_Year": "2023",
      "Current_Insurer": "บริษัท E (Eco Guard)",
      "Current_Policy_Type": "ชั้น 2+",
      "Current_Premium_THB": "฿9,794",
      "Policy_Expiry_Date": "2026-09-18",
      "Days_To_Expiry": "3",
      "Contact_Status": "ติดต่อแล้ว-สนใจเปรียบเทียบ",
      "Historical_Renewal_Behavior": "ชอบเปลี่ยนบริษัทประกันเพื่อราคา",
      "premium": 9794,
      "daysToExpiryRaw": 3,
      "carYear": 2023
    },
    {
      "Customer_ID": "CUST-0046",
      "Customer_Name": "คุณลูกค้า 46",
      "Phone_Number": "0895-796-6188",
      "Car_Brand": "BMW",
      "Car_Model": "330e",
      "Car_Year": "2021",
      "Current_Insurer": "บริษัท A (ANC Shield)",
      "Current_Policy_Type": "ชั้น 1",
      "Current_Premium_THB": "฿41,245",
      "Policy_Expiry_Date": "2026-09-29",
      "Days_To_Expiry": "14",
      "Contact_Status": "ติดต่อแล้ว-สนใจเปรียบเทียบ",
      "Historical_Renewal_Behavior": "ต่ออายุเฉียดฉิว",
      "premium": 41245,
      "daysToExpiryRaw": 14,
      "carYear": 2021
    },
    {
      "Customer_ID": "CUST-0047",
      "Customer_Name": "คุณลูกค้า 47",
      "Phone_Number": "0857-440-8421",
      "Car_Brand": "BMW",
      "Car_Model": "X3",
      "Car_Year": "2020",
      "Current_Insurer": "บริษัท E (Eco Guard)",
      "Current_Policy_Type": "ชั้น 1",
      "Current_Premium_THB": "฿42,069",
      "Policy_Expiry_Date": "2026-09-29",
      "Days_To_Expiry": "14",
      "Contact_Status": "ยังไม่ได้ติดต่อ",
      "Historical_Renewal_Behavior": "ชอบเปลี่ยนบริษัทประกันเพื่อราคา",
      "premium": 42069,
      "daysToExpiryRaw": 14,
      "carYear": 2020
    },
    {
      "Customer_ID": "CUST-0048",
      "Customer_Name": "คุณลูกค้า 48",
      "Phone_Number": "0819-861-3489",
      "Car_Brand": "Mercedes-Benz",
      "Car_Model": "C220d",
      "Car_Year": "2020",
      "Current_Insurer": "บริษัท A (ANC Shield)",
      "Current_Policy_Type": "ชั้น 1",
      "Current_Premium_THB": "฿44,364",
      "Policy_Expiry_Date": "2026-09-20",
      "Days_To_Expiry": "5",
      "Contact_Status": "ยังไม่ได้ติดต่อ",
      "Historical_Renewal_Behavior": "ชอบเปลี่ยนบริษัทประกันเพื่อราคา",
      "premium": 44364,
      "daysToExpiryRaw": 5,
      "carYear": 2020
    },
    {
      "Customer_ID": "CUST-0049",
      "Customer_Name": "คุณลูกค้า 49",
      "Phone_Number": "0811-596-7303",
      "Car_Brand": "Mercedes-Benz",
      "Car_Model": "E300e",
      "Car_Year": "2019",
      "Current_Insurer": "บริษัท C (Thai Auto)",
      "Current_Policy_Type": "ชั้น 2+",
      "Current_Premium_THB": "฿34,833",
      "Policy_Expiry_Date": "2026-09-25",
      "Days_To_Expiry": "10",
      "Contact_Status": "ยังไม่ได้ติดต่อ",
      "Historical_Renewal_Behavior": "ต่ออายุตรงเวลาเสมอ",
      "premium": 34833,
      "daysToExpiryRaw": 10,
      "carYear": 2019
    },
    {
      "Customer_ID": "CUST-0050",
      "Customer_Name": "คุณลูกค้า 50",
      "Phone_Number": "0860-526-6732",
      "Car_Brand": "Tesla",
      "Car_Model": "Model 3",
      "Car_Year": "2023",
      "Current_Insurer": "บริษัท D (Premium Care)",
      "Current_Policy_Type": "ชั้น 1",
      "Current_Premium_THB": "฿33,536",
      "Policy_Expiry_Date": "2026-09-29",
      "Days_To_Expiry": "14",
      "Contact_Status": "ยังไม่ได้ติดต่อ",
      "Historical_Renewal_Behavior": "ต่ออายุตรงเวลาเสมอ",
      "premium": 33536,
      "daysToExpiryRaw": 14,
      "carYear": 2023
    },
    {
      "Customer_ID": "CUST-0051",
      "Customer_Name": "คุณลูกค้า 51",
      "Phone_Number": "0822-111-6726",
      "Car_Brand": "Tesla",
      "Car_Model": "Model Y",
      "Car_Year": "2023",
      "Current_Insurer": "บริษัท B (Safety Plus)",
      "Current_Policy_Type": "ชั้น 1",
      "Current_Premium_THB": "฿30,082",
      "Policy_Expiry_Date": "2026-09-22",
      "Days_To_Expiry": "7",
      "Contact_Status": "ติดต่อแล้ว-ขอส่วนลด",
      "Historical_Renewal_Behavior": "ต่ออายุตรงเวลาเสมอ",
      "premium": 30082,
      "daysToExpiryRaw": 7,
      "carYear": 2023
    },
    {
      "Customer_ID": "CUST-0052",
      "Customer_Name": "คุณลูกค้า 52",
      "Phone_Number": "0835-701-1417",
      "Car_Brand": "Toyota",
      "Car_Model": "Camry",
      "Car_Year": "2018",
      "Current_Insurer": "บริษัท C (Thai Auto)",
      "Current_Policy_Type": "ชั้น 1",
      "Current_Premium_THB": "฿18,267",
      "Policy_Expiry_Date": "2026-09-29",
      "Days_To_Expiry": "14",
      "Contact_Status": "ยังไม่ได้ติดต่อ",
      "Historical_Renewal_Behavior": "ชอบเปลี่ยนบริษัทประกันเพื่อราคา",
      "premium": 18267,
      "daysToExpiryRaw": 14,
      "carYear": 2018
    },
    {
      "Customer_ID": "CUST-0053",
      "Customer_Name": "คุณลูกค้า 53",
      "Phone_Number": "0838-475-8587",
      "Car_Brand": "Toyota",
      "Car_Model": "Corolla Altis",
      "Car_Year": "2020",
      "Current_Insurer": "บริษัท A (ANC Shield)",
      "Current_Policy_Type": "ชั้น 2+",
      "Current_Premium_THB": "฿10,308",
      "Policy_Expiry_Date": "2026-09-25",
      "Days_To_Expiry": "10",
      "Contact_Status": "ติดต่อแล้ว-สนใจเปรียบเทียบ",
      "Historical_Renewal_Behavior": "เคยมีประวัติเคลมหนัก",
      "premium": 10308,
      "daysToExpiryRaw": 10,
      "carYear": 2020
    },
    {
      "Customer_ID": "CUST-0054",
      "Customer_Name": "คุณลูกค้า 54",
      "Phone_Number": "0873-838-2122",
      "Car_Brand": "Toyota",
      "Car_Model": "Yaris Ativ",
      "Car_Year": "2022",
      "Current_Insurer": "บริษัท D (Premium Care)",
      "Current_Policy_Type": "ชั้น 1",
      "Current_Premium_THB": "฿17,143",
      "Policy_Expiry_Date": "2026-09-22",
      "Days_To_Expiry": "7",
      "Contact_Status": "ติดต่อแล้ว-ปฏิเสธ",
      "Historical_Renewal_Behavior": "ต่ออายุตรงเวลาเสมอ",
      "premium": 17143,
      "daysToExpiryRaw": 7,
      "carYear": 2022
    },
    {
      "Customer_ID": "CUST-0055",
      "Customer_Name": "คุณลูกค้า 55",
      "Phone_Number": "0821-468-4766",
      "Car_Brand": "Toyota",
      "Car_Model": "Fortuner",
      "Car_Year": "2019",
      "Current_Insurer": "บริษัท E (Eco Guard)",
      "Current_Policy_Type": "ชั้น 2+",
      "Current_Premium_THB": "฿10,414",
      "Policy_Expiry_Date": "2026-09-20",
      "Days_To_Expiry": "5",
      "Contact_Status": "ติดต่อแล้ว-ปฏิเสธ",
      "Historical_Renewal_Behavior": "ต่ออายุเฉียดฉิว",
      "premium": 10414,
      "daysToExpiryRaw": 5,
      "carYear": 2019
    },
    {
      "Customer_ID": "CUST-0056",
      "Customer_Name": "คุณลูกค้า 56",
      "Phone_Number": "0893-979-1728",
      "Car_Brand": "Toyota",
      "Car_Model": "Hilux Revo",
      "Car_Year": "2021",
      "Current_Insurer": "บริษัท E (Eco Guard)",
      "Current_Policy_Type": "ชั้น 2+",
      "Current_Premium_THB": "฿7,895",
      "Policy_Expiry_Date": "2026-10-30",
      "Days_To_Expiry": "45",
      "Contact_Status": "ติดต่อแล้ว-ลังเล",
      "Historical_Renewal_Behavior": "ต่ออายุตรงเวลาเสมอ",
      "premium": 7895,
      "daysToExpiryRaw": 45,
      "carYear": 2021
    },
    {
      "Customer_ID": "CUST-0057",
      "Customer_Name": "คุณลูกค้า 57",
      "Phone_Number": "0880-895-1717",
      "Car_Brand": "Honda",
      "Car_Model": "Civic",
      "Car_Year": "2020",
      "Current_Insurer": "บริษัท D (Premium Care)",
      "Current_Policy_Type": "ชั้น 1",
      "Current_Premium_THB": "฿20,486",
      "Policy_Expiry_Date": "2026-09-18",
      "Days_To_Expiry": "3",
      "Contact_Status": "ยังไม่ได้ติดต่อ",
      "Historical_Renewal_Behavior": "เคยมีประวัติเคลมหนัก",
      "premium": 20486,
      "daysToExpiryRaw": 3,
      "carYear": 2020
    },
    {
      "Customer_ID": "CUST-0058",
      "Customer_Name": "คุณลูกค้า 58",
      "Phone_Number": "0834-990-6588",
      "Car_Brand": "Honda",
      "Car_Model": "City",
      "Car_Year": "2021",
      "Current_Insurer": "บริษัท D (Premium Care)",
      "Current_Policy_Type": "ชั้น 3+",
      "Current_Premium_THB": "฿8,667",
      "Policy_Expiry_Date": "2026-10-06",
      "Days_To_Expiry": "21",
      "Contact_Status": "ยังไม่ได้ติดต่อ",
      "Historical_Renewal_Behavior": "ต่ออายุเฉียดฉิว",
      "premium": 8667,
      "daysToExpiryRaw": 21,
      "carYear": 2021
    },
    {
      "Customer_ID": "CUST-0059",
      "Customer_Name": "คุณลูกค้า 59",
      "Phone_Number": "0867-497-5729",
      "Car_Brand": "Honda",
      "Car_Model": "CR-V",
      "Car_Year": "2019",
      "Current_Insurer": "บริษัท E (Eco Guard)",
      "Current_Policy_Type": "ชั้น 2+",
      "Current_Premium_THB": "฿8,232",
      "Policy_Expiry_Date": "2026-09-22",
      "Days_To_Expiry": "7",
      "Contact_Status": "ยังไม่ได้ติดต่อ",
      "Historical_Renewal_Behavior": "เคยมีประวัติเคลมหนัก",
      "premium": 8232,
      "daysToExpiryRaw": 7,
      "carYear": 2019
    },
    {
      "Customer_ID": "CUST-0060",
      "Customer_Name": "คุณลูกค้า 60",
      "Phone_Number": "0818-173-1953",
      "Car_Brand": "Honda",
      "Car_Model": "HR-V",
      "Car_Year": "2022",
      "Current_Insurer": "บริษัท D (Premium Care)",
      "Current_Policy_Type": "ชั้น 2+",
      "Current_Premium_THB": "฿10,801",
      "Policy_Expiry_Date": "2026-09-18",
      "Days_To_Expiry": "3",
      "Contact_Status": "ติดต่อแล้ว-ขอส่วนลด",
      "Historical_Renewal_Behavior": "ต่ออายุเฉียดฉิว",
      "premium": 10801,
      "daysToExpiryRaw": 3,
      "carYear": 2022
    },
    {
      "Customer_ID": "CUST-0061",
      "Customer_Name": "คุณลูกค้า 61",
      "Phone_Number": "0818-894-3681",
      "Car_Brand": "Mazda",
      "Car_Model": "CX-5",
      "Car_Year": "2018",
      "Current_Insurer": "บริษัท B (Safety Plus)",
      "Current_Policy_Type": "ชั้น 1",
      "Current_Premium_THB": "฿20,541",
      "Policy_Expiry_Date": "2026-11-14",
      "Days_To_Expiry": "60",
      "Contact_Status": "ยังไม่ได้ติดต่อ",
      "Historical_Renewal_Behavior": "ต่ออายุตรงเวลาเสมอ",
      "premium": 20541,
      "daysToExpiryRaw": 60,
      "carYear": 2018
    },
    {
      "Customer_ID": "CUST-0062",
      "Customer_Name": "คุณลูกค้า 62",
      "Phone_Number": "0895-599-9702",
      "Car_Brand": "Mazda",
      "Car_Model": "Mazda 3",
      "Car_Year": "2020",
      "Current_Insurer": "บริษัท A (ANC Shield)",
      "Current_Policy_Type": "ชั้น 1",
      "Current_Premium_THB": "฿18,141",
      "Policy_Expiry_Date": "2026-09-29",
      "Days_To_Expiry": "14",
      "Contact_Status": "ติดต่อแล้ว-สนใจเปรียบเทียบ",
      "Historical_Renewal_Behavior": "เคยมีประวัติเคลมหนัก",
      "premium": 18141,
      "daysToExpiryRaw": 14,
      "carYear": 2020
    },
    {
      "Customer_ID": "CUST-0063",
      "Customer_Name": "คุณลูกค้า 63",
      "Phone_Number": "0863-266-5186",
      "Car_Brand": "Mazda",
      "Car_Model": "CX-30",
      "Car_Year": "2021",
      "Current_Insurer": "บริษัท B (Safety Plus)",
      "Current_Policy_Type": "ชั้น 3+",
      "Current_Premium_THB": "฿11,634",
      "Policy_Expiry_Date": "2026-09-22",
      "Days_To_Expiry": "7",
      "Contact_Status": "ยังไม่ได้ติดต่อ",
      "Historical_Renewal_Behavior": "ต่ออายุเฉียดฉิว",
      "premium": 11634,
      "daysToExpiryRaw": 7,
      "carYear": 2021
    },
    {
      "Customer_ID": "CUST-0064",
      "Customer_Name": "คุณลูกค้า 64",
      "Phone_Number": "0867-759-7619",
      "Car_Brand": "Isuzu",
      "Car_Model": "D-Max",
      "Car_Year": "2020",
      "Current_Insurer": "บริษัท E (Eco Guard)",
      "Current_Policy_Type": "ชั้น 2+",
      "Current_Premium_THB": "฿9,458",
      "Policy_Expiry_Date": "2026-09-29",
      "Days_To_Expiry": "14",
      "Contact_Status": "ติดต่อแล้ว-สนใจเปรียบเทียบ",
      "Historical_Renewal_Behavior": "ต่ออายุเฉียดฉิว",
      "premium": 9458,
      "daysToExpiryRaw": 14,
      "carYear": 2020
    },
    {
      "Customer_ID": "CUST-0065",
      "Customer_Name": "คุณลูกค้า 65",
      "Phone_Number": "0872-607-8576",
      "Car_Brand": "Isuzu",
      "Car_Model": "Mu-X",
      "Car_Year": "2019",
      "Current_Insurer": "บริษัท A (ANC Shield)",
      "Current_Policy_Type": "ชั้น 1",
      "Current_Premium_THB": "฿15,133",
      "Policy_Expiry_Date": "2026-10-06",
      "Days_To_Expiry": "21",
      "Contact_Status": "ติดต่อแล้ว-ปฏิเสธ",
      "Historical_Renewal_Behavior": "ต่ออายุตรงเวลาเสมอ",
      "premium": 15133,
      "daysToExpiryRaw": 21,
      "carYear": 2019
    },
    {
      "Customer_ID": "CUST-0066",
      "Customer_Name": "คุณลูกค้า 66",
      "Phone_Number": "0870-914-5175",
      "Car_Brand": "Nissan",
      "Car_Model": "Almera",
      "Car_Year": "2021",
      "Current_Insurer": "บริษัท E (Eco Guard)",
      "Current_Policy_Type": "ชั้น 3+",
      "Current_Premium_THB": "฿8,750",
      "Policy_Expiry_Date": "2026-09-29",
      "Days_To_Expiry": "14",
      "Contact_Status": "ยังไม่ได้ติดต่อ",
      "Historical_Renewal_Behavior": "ชอบเปลี่ยนบริษัทประกันเพื่อราคา",
      "premium": 8750,
      "daysToExpiryRaw": 14,
      "carYear": 2021
    },
    {
      "Customer_ID": "CUST-0067",
      "Customer_Name": "คุณลูกค้า 67",
      "Phone_Number": "0858-625-4486",
      "Car_Brand": "Nissan",
      "Car_Model": "Kicks",
      "Car_Year": "2022",
      "Current_Insurer": "บริษัท A (ANC Shield)",
      "Current_Policy_Type": "ชั้น 2+",
      "Current_Premium_THB": "฿10,830",
      "Policy_Expiry_Date": "2026-10-15",
      "Days_To_Expiry": "30",
      "Contact_Status": "ยังไม่ได้ติดต่อ",
      "Historical_Renewal_Behavior": "เคยมีประวัติเคลมหนัก",
      "premium": 10830,
      "daysToExpiryRaw": 30,
      "carYear": 2022
    },
    {
      "Customer_ID": "CUST-0068",
      "Customer_Name": "คุณลูกค้า 68",
      "Phone_Number": "0883-835-6063",
      "Car_Brand": "MG",
      "Car_Model": "ZS",
      "Car_Year": "2021",
      "Current_Insurer": "บริษัท D (Premium Care)",
      "Current_Policy_Type": "ชั้น 1",
      "Current_Premium_THB": "฿19,468",
      "Policy_Expiry_Date": "2026-09-22",
      "Days_To_Expiry": "7",
      "Contact_Status": "ยังไม่ได้ติดต่อ",
      "Historical_Renewal_Behavior": "ต่ออายุเฉียดฉิว",
      "premium": 19468,
      "daysToExpiryRaw": 7,
      "carYear": 2021
    },
    {
      "Customer_ID": "CUST-0069",
      "Customer_Name": "คุณลูกค้า 69",
      "Phone_Number": "0817-797-8483",
      "Car_Brand": "MG",
      "Car_Model": "4 EV",
      "Car_Year": "2023",
      "Current_Insurer": "บริษัท B (Safety Plus)",
      "Current_Policy_Type": "ชั้น 1",
      "Current_Premium_THB": "฿19,964",
      "Policy_Expiry_Date": "2026-11-14",
      "Days_To_Expiry": "60",
      "Contact_Status": "ติดต่อแล้ว-ปฏิเสธ",
      "Historical_Renewal_Behavior": "ต่ออายุเฉียดฉิว",
      "premium": 19964,
      "daysToExpiryRaw": 60,
      "carYear": 2023
    },
    {
      "Customer_ID": "CUST-0070",
      "Customer_Name": "คุณลูกค้า 70",
      "Phone_Number": "0872-244-6320",
      "Car_Brand": "BYD",
      "Car_Model": "Atto 3",
      "Car_Year": "2023",
      "Current_Insurer": "บริษัท A (ANC Shield)",
      "Current_Policy_Type": "ชั้น 1",
      "Current_Premium_THB": "฿17,779",
      "Policy_Expiry_Date": "2026-09-22",
      "Days_To_Expiry": "7",
      "Contact_Status": "ยังไม่ได้ติดต่อ",
      "Historical_Renewal_Behavior": "ชอบเปลี่ยนบริษัทประกันเพื่อราคา",
      "premium": 17779,
      "daysToExpiryRaw": 7,
      "carYear": 2023
    },
    {
      "Customer_ID": "CUST-0071",
      "Customer_Name": "คุณลูกค้า 71",
      "Phone_Number": "0815-693-8026",
      "Car_Brand": "BYD",
      "Car_Model": "Dolphin",
      "Car_Year": "2023",
      "Current_Insurer": "บริษัท E (Eco Guard)",
      "Current_Policy_Type": "ชั้น 2+",
      "Current_Premium_THB": "฿7,509",
      "Policy_Expiry_Date": "2026-10-30",
      "Days_To_Expiry": "45",
      "Contact_Status": "ติดต่อแล้ว-ลังเล",
      "Historical_Renewal_Behavior": "ต่ออายุตรงเวลาเสมอ",
      "premium": 7509,
      "daysToExpiryRaw": 45,
      "carYear": 2023
    },
    {
      "Customer_ID": "CUST-0072",
      "Customer_Name": "คุณลูกค้า 72",
      "Phone_Number": "0814-218-2015",
      "Car_Brand": "BMW",
      "Car_Model": "330e",
      "Car_Year": "2021",
      "Current_Insurer": "บริษัท A (ANC Shield)",
      "Current_Policy_Type": "ชั้น 2+",
      "Current_Premium_THB": "฿30,193",
      "Policy_Expiry_Date": "2026-11-14",
      "Days_To_Expiry": "60",
      "Contact_Status": "ยังไม่ได้ติดต่อ",
      "Historical_Renewal_Behavior": "ต่ออายุตรงเวลาเสมอ",
      "premium": 30193,
      "daysToExpiryRaw": 60,
      "carYear": 2021
    },
    {
      "Customer_ID": "CUST-0073",
      "Customer_Name": "คุณลูกค้า 73",
      "Phone_Number": "0835-162-4925",
      "Car_Brand": "BMW",
      "Car_Model": "X3",
      "Car_Year": "2020",
      "Current_Insurer": "บริษัท C (Thai Auto)",
      "Current_Policy_Type": "ชั้น 2+",
      "Current_Premium_THB": "฿41,772",
      "Policy_Expiry_Date": "2026-09-18",
      "Days_To_Expiry": "3",
      "Contact_Status": "ยังไม่ได้ติดต่อ",
      "Historical_Renewal_Behavior": "ชอบเปลี่ยนบริษัทประกันเพื่อราคา",
      "premium": 41772,
      "daysToExpiryRaw": 3,
      "carYear": 2020
    },
    {
      "Customer_ID": "CUST-0074",
      "Customer_Name": "คุณลูกค้า 74",
      "Phone_Number": "0810-504-9175",
      "Car_Brand": "Mercedes-Benz",
      "Car_Model": "C220d",
      "Car_Year": "2020",
      "Current_Insurer": "บริษัท D (Premium Care)",
      "Current_Policy_Type": "ชั้น 2+",
      "Current_Premium_THB": "฿37,860",
      "Policy_Expiry_Date": "2026-11-14",
      "Days_To_Expiry": "60",
      "Contact_Status": "ติดต่อแล้ว-สนใจเปรียบเทียบ",
      "Historical_Renewal_Behavior": "ต่ออายุตรงเวลาเสมอ",
      "premium": 37860,
      "daysToExpiryRaw": 60,
      "carYear": 2020
    },
    {
      "Customer_ID": "CUST-0075",
      "Customer_Name": "คุณลูกค้า 75",
      "Phone_Number": "0862-776-5809",
      "Car_Brand": "Mercedes-Benz",
      "Car_Model": "E300e",
      "Car_Year": "2019",
      "Current_Insurer": "บริษัท B (Safety Plus)",
      "Current_Policy_Type": "ชั้น 1",
      "Current_Premium_THB": "฿43,444",
      "Policy_Expiry_Date": "2026-09-25",
      "Days_To_Expiry": "10",
      "Contact_Status": "ยังไม่ได้ติดต่อ",
      "Historical_Renewal_Behavior": "ชอบเปลี่ยนบริษัทประกันเพื่อราคา",
      "premium": 43444,
      "daysToExpiryRaw": 10,
      "carYear": 2019
    },
    {
      "Customer_ID": "CUST-0076",
      "Customer_Name": "คุณลูกค้า 76",
      "Phone_Number": "0854-816-8939",
      "Car_Brand": "Tesla",
      "Car_Model": "Model 3",
      "Car_Year": "2023",
      "Current_Insurer": "บริษัท A (ANC Shield)",
      "Current_Policy_Type": "ชั้น 2+",
      "Current_Premium_THB": "฿38,015",
      "Policy_Expiry_Date": "2026-09-18",
      "Days_To_Expiry": "3",
      "Contact_Status": "ยังไม่ได้ติดต่อ",
      "Historical_Renewal_Behavior": "ชอบเปลี่ยนบริษัทประกันเพื่อราคา",
      "premium": 38015,
      "daysToExpiryRaw": 3,
      "carYear": 2023
    },
    {
      "Customer_ID": "CUST-0077",
      "Customer_Name": "คุณลูกค้า 77",
      "Phone_Number": "0835-349-9865",
      "Car_Brand": "Tesla",
      "Car_Model": "Model Y",
      "Car_Year": "2023",
      "Current_Insurer": "บริษัท C (Thai Auto)",
      "Current_Policy_Type": "ชั้น 1",
      "Current_Premium_THB": "฿32,363",
      "Policy_Expiry_Date": "2026-10-06",
      "Days_To_Expiry": "21",
      "Contact_Status": "ติดต่อแล้ว-ปฏิเสธ",
      "Historical_Renewal_Behavior": "ต่ออายุเฉียดฉิว",
      "premium": 32363,
      "daysToExpiryRaw": 21,
      "carYear": 2023
    },
    {
      "Customer_ID": "CUST-0078",
      "Customer_Name": "คุณลูกค้า 78",
      "Phone_Number": "0866-500-5719",
      "Car_Brand": "Toyota",
      "Car_Model": "Camry",
      "Car_Year": "2018",
      "Current_Insurer": "บริษัท E (Eco Guard)",
      "Current_Policy_Type": "ชั้น 2+",
      "Current_Premium_THB": "฿12,173",
      "Policy_Expiry_Date": "2026-10-06",
      "Days_To_Expiry": "21",
      "Contact_Status": "ติดต่อแล้ว-ปฏิเสธ",
      "Historical_Renewal_Behavior": "เคยมีประวัติเคลมหนัก",
      "premium": 12173,
      "daysToExpiryRaw": 21,
      "carYear": 2018
    },
    {
      "Customer_ID": "CUST-0079",
      "Customer_Name": "คุณลูกค้า 79",
      "Phone_Number": "0847-405-7241",
      "Car_Brand": "Toyota",
      "Car_Model": "Corolla Altis",
      "Car_Year": "2020",
      "Current_Insurer": "บริษัท B (Safety Plus)",
      "Current_Policy_Type": "ชั้น 1",
      "Current_Premium_THB": "฿22,002",
      "Policy_Expiry_Date": "2026-09-18",
      "Days_To_Expiry": "3",
      "Contact_Status": "ติดต่อแล้ว-ขอส่วนลด",
      "Historical_Renewal_Behavior": "ต่ออายุตรงเวลาเสมอ",
      "premium": 22002,
      "daysToExpiryRaw": 3,
      "carYear": 2020
    },
    {
      "Customer_ID": "CUST-0080",
      "Customer_Name": "คุณลูกค้า 80",
      "Phone_Number": "0847-580-6115",
      "Car_Brand": "Toyota",
      "Car_Model": "Yaris Ativ",
      "Car_Year": "2022",
      "Current_Insurer": "บริษัท B (Safety Plus)",
      "Current_Policy_Type": "ชั้น 2+",
      "Current_Premium_THB": "฿9,680",
      "Policy_Expiry_Date": "2026-10-06",
      "Days_To_Expiry": "21",
      "Contact_Status": "ติดต่อแล้ว-สนใจเปรียบเทียบ",
      "Historical_Renewal_Behavior": "ต่ออายุตรงเวลาเสมอ",
      "premium": 9680,
      "daysToExpiryRaw": 21,
      "carYear": 2022
    },
    {
      "Customer_ID": "CUST-0081",
      "Customer_Name": "คุณลูกค้า 81",
      "Phone_Number": "0883-884-4579",
      "Car_Brand": "Toyota",
      "Car_Model": "Fortuner",
      "Car_Year": "2019",
      "Current_Insurer": "บริษัท D (Premium Care)",
      "Current_Policy_Type": "ชั้น 1",
      "Current_Premium_THB": "฿22,941",
      "Policy_Expiry_Date": "2026-09-25",
      "Days_To_Expiry": "10",
      "Contact_Status": "ยังไม่ได้ติดต่อ",
      "Historical_Renewal_Behavior": "ชอบเปลี่ยนบริษัทประกันเพื่อราคา",
      "premium": 22941,
      "daysToExpiryRaw": 10,
      "carYear": 2019
    },
    {
      "Customer_ID": "CUST-0082",
      "Customer_Name": "คุณลูกค้า 82",
      "Phone_Number": "0852-851-2906",
      "Car_Brand": "Toyota",
      "Car_Model": "Hilux Revo",
      "Car_Year": "2021",
      "Current_Insurer": "บริษัท A (ANC Shield)",
      "Current_Policy_Type": "ชั้น 1",
      "Current_Premium_THB": "฿21,238",
      "Policy_Expiry_Date": "2026-09-22",
      "Days_To_Expiry": "7",
      "Contact_Status": "ติดต่อแล้ว-ขอส่วนลด",
      "Historical_Renewal_Behavior": "เคยมีประวัติเคลมหนัก",
      "premium": 21238,
      "daysToExpiryRaw": 7,
      "carYear": 2021
    },
    {
      "Customer_ID": "CUST-0083",
      "Customer_Name": "คุณลูกค้า 83",
      "Phone_Number": "0813-795-9472",
      "Car_Brand": "Honda",
      "Car_Model": "Civic",
      "Car_Year": "2020",
      "Current_Insurer": "บริษัท C (Thai Auto)",
      "Current_Policy_Type": "ชั้น 2+",
      "Current_Premium_THB": "฿8,166",
      "Policy_Expiry_Date": "2026-09-29",
      "Days_To_Expiry": "14",
      "Contact_Status": "ยังไม่ได้ติดต่อ",
      "Historical_Renewal_Behavior": "ต่ออายุเฉียดฉิว",
      "premium": 8166,
      "daysToExpiryRaw": 14,
      "carYear": 2020
    },
    {
      "Customer_ID": "CUST-0084",
      "Customer_Name": "คุณลูกค้า 84",
      "Phone_Number": "0860-502-8956",
      "Car_Brand": "Honda",
      "Car_Model": "City",
      "Car_Year": "2021",
      "Current_Insurer": "บริษัท E (Eco Guard)",
      "Current_Policy_Type": "ชั้น 1",
      "Current_Premium_THB": "฿19,777",
      "Policy_Expiry_Date": "2026-09-20",
      "Days_To_Expiry": "5",
      "Contact_Status": "ยังไม่ได้ติดต่อ",
      "Historical_Renewal_Behavior": "ต่ออายุตรงเวลาเสมอ",
      "premium": 19777,
      "daysToExpiryRaw": 5,
      "carYear": 2021
    },
    {
      "Customer_ID": "CUST-0085",
      "Customer_Name": "คุณลูกค้า 85",
      "Phone_Number": "0814-332-1523",
      "Car_Brand": "Honda",
      "Car_Model": "CR-V",
      "Car_Year": "2019",
      "Current_Insurer": "บริษัท B (Safety Plus)",
      "Current_Policy_Type": "ชั้น 2+",
      "Current_Premium_THB": "฿9,468",
      "Policy_Expiry_Date": "2026-09-25",
      "Days_To_Expiry": "10",
      "Contact_Status": "ติดต่อแล้ว-ขอส่วนลด",
      "Historical_Renewal_Behavior": "ต่ออายุตรงเวลาเสมอ",
      "premium": 9468,
      "daysToExpiryRaw": 10,
      "carYear": 2019
    },
    {
      "Customer_ID": "CUST-0086",
      "Customer_Name": "คุณลูกค้า 86",
      "Phone_Number": "0835-348-7190",
      "Car_Brand": "Honda",
      "Car_Model": "HR-V",
      "Car_Year": "2022",
      "Current_Insurer": "บริษัท A (ANC Shield)",
      "Current_Policy_Type": "ชั้น 2+",
      "Current_Premium_THB": "฿11,702",
      "Policy_Expiry_Date": "2026-10-15",
      "Days_To_Expiry": "30",
      "Contact_Status": "ยังไม่ได้ติดต่อ",
      "Historical_Renewal_Behavior": "ต่ออายุเฉียดฉิว",
      "premium": 11702,
      "daysToExpiryRaw": 30,
      "carYear": 2022
    },
    {
      "Customer_ID": "CUST-0087",
      "Customer_Name": "คุณลูกค้า 87",
      "Phone_Number": "0845-356-2276",
      "Car_Brand": "Mazda",
      "Car_Model": "CX-5",
      "Car_Year": "2018",
      "Current_Insurer": "บริษัท D (Premium Care)",
      "Current_Policy_Type": "ชั้น 1",
      "Current_Premium_THB": "฿15,638",
      "Policy_Expiry_Date": "2026-10-15",
      "Days_To_Expiry": "30",
      "Contact_Status": "ยังไม่ได้ติดต่อ",
      "Historical_Renewal_Behavior": "เคยมีประวัติเคลมหนัก",
      "premium": 15638,
      "daysToExpiryRaw": 30,
      "carYear": 2018
    },
    {
      "Customer_ID": "CUST-0088",
      "Customer_Name": "คุณลูกค้า 88",
      "Phone_Number": "0896-177-1364",
      "Car_Brand": "Mazda",
      "Car_Model": "Mazda 3",
      "Car_Year": "2020",
      "Current_Insurer": "บริษัท B (Safety Plus)",
      "Current_Policy_Type": "ชั้น 1",
      "Current_Premium_THB": "฿20,126",
      "Policy_Expiry_Date": "2026-09-29",
      "Days_To_Expiry": "14",
      "Contact_Status": "ติดต่อแล้ว-ลังเล",
      "Historical_Renewal_Behavior": "ชอบเปลี่ยนบริษัทประกันเพื่อราคา",
      "premium": 20126,
      "daysToExpiryRaw": 14,
      "carYear": 2020
    },
    {
      "Customer_ID": "CUST-0089",
      "Customer_Name": "คุณลูกค้า 89",
      "Phone_Number": "0827-605-7949",
      "Car_Brand": "Mazda",
      "Car_Model": "CX-30",
      "Car_Year": "2021",
      "Current_Insurer": "บริษัท C (Thai Auto)",
      "Current_Policy_Type": "ชั้น 1",
      "Current_Premium_THB": "฿23,152",
      "Policy_Expiry_Date": "2026-09-29",
      "Days_To_Expiry": "14",
      "Contact_Status": "ยังไม่ได้ติดต่อ",
      "Historical_Renewal_Behavior": "ชอบเปลี่ยนบริษัทประกันเพื่อราคา",
      "premium": 23152,
      "daysToExpiryRaw": 14,
      "carYear": 2021
    },
    {
      "Customer_ID": "CUST-0090",
      "Customer_Name": "คุณลูกค้า 90",
      "Phone_Number": "0866-372-7229",
      "Car_Brand": "Isuzu",
      "Car_Model": "D-Max",
      "Car_Year": "2020",
      "Current_Insurer": "บริษัท B (Safety Plus)",
      "Current_Policy_Type": "ชั้น 1",
      "Current_Premium_THB": "฿19,632",
      "Policy_Expiry_Date": "2026-10-15",
      "Days_To_Expiry": "30",
      "Contact_Status": "ติดต่อแล้ว-สนใจเปรียบเทียบ",
      "Historical_Renewal_Behavior": "เคยมีประวัติเคลมหนัก",
      "premium": 19632,
      "daysToExpiryRaw": 30,
      "carYear": 2020
    },
    {
      "Customer_ID": "CUST-0091",
      "Customer_Name": "คุณลูกค้า 91",
      "Phone_Number": "0819-166-1232",
      "Car_Brand": "Isuzu",
      "Car_Model": "Mu-X",
      "Car_Year": "2019",
      "Current_Insurer": "บริษัท E (Eco Guard)",
      "Current_Policy_Type": "ชั้น 1",
      "Current_Premium_THB": "฿21,371",
      "Policy_Expiry_Date": "2026-09-25",
      "Days_To_Expiry": "10",
      "Contact_Status": "ติดต่อแล้ว-สนใจเปรียบเทียบ",
      "Historical_Renewal_Behavior": "เคยมีประวัติเคลมหนัก",
      "premium": 21371,
      "daysToExpiryRaw": 10,
      "carYear": 2019
    },
    {
      "Customer_ID": "CUST-0092",
      "Customer_Name": "คุณลูกค้า 92",
      "Phone_Number": "0849-468-7891",
      "Car_Brand": "Nissan",
      "Car_Model": "Almera",
      "Car_Year": "2021",
      "Current_Insurer": "บริษัท C (Thai Auto)",
      "Current_Policy_Type": "ชั้น 1",
      "Current_Premium_THB": "฿17,739",
      "Policy_Expiry_Date": "2026-09-29",
      "Days_To_Expiry": "14",
      "Contact_Status": "ติดต่อแล้ว-สนใจเปรียบเทียบ",
      "Historical_Renewal_Behavior": "เคยมีประวัติเคลมหนัก",
      "premium": 17739,
      "daysToExpiryRaw": 14,
      "carYear": 2021
    },
    {
      "Customer_ID": "CUST-0093",
      "Customer_Name": "คุณลูกค้า 93",
      "Phone_Number": "0868-976-4812",
      "Car_Brand": "Nissan",
      "Car_Model": "Kicks",
      "Car_Year": "2022",
      "Current_Insurer": "บริษัท A (ANC Shield)",
      "Current_Policy_Type": "ชั้น 1",
      "Current_Premium_THB": "฿16,733",
      "Policy_Expiry_Date": "2026-09-22",
      "Days_To_Expiry": "7",
      "Contact_Status": "ติดต่อแล้ว-สนใจเปรียบเทียบ",
      "Historical_Renewal_Behavior": "ต่ออายุเฉียดฉิว",
      "premium": 16733,
      "daysToExpiryRaw": 7,
      "carYear": 2022
    },
    {
      "Customer_ID": "CUST-0094",
      "Customer_Name": "คุณลูกค้า 94",
      "Phone_Number": "0884-545-4735",
      "Car_Brand": "MG",
      "Car_Model": "ZS",
      "Car_Year": "2021",
      "Current_Insurer": "บริษัท A (ANC Shield)",
      "Current_Policy_Type": "ชั้น 1",
      "Current_Premium_THB": "฿23,434",
      "Policy_Expiry_Date": "2026-09-18",
      "Days_To_Expiry": "3",
      "Contact_Status": "ติดต่อแล้ว-ขอส่วนลด",
      "Historical_Renewal_Behavior": "เคยมีประวัติเคลมหนัก",
      "premium": 23434,
      "daysToExpiryRaw": 3,
      "carYear": 2021
    },
    {
      "Customer_ID": "CUST-0095",
      "Customer_Name": "คุณลูกค้า 95",
      "Phone_Number": "0815-421-9659",
      "Car_Brand": "MG",
      "Car_Model": "4 EV",
      "Car_Year": "2023",
      "Current_Insurer": "บริษัท D (Premium Care)",
      "Current_Policy_Type": "ชั้น 3+",
      "Current_Premium_THB": "฿8,145",
      "Policy_Expiry_Date": "2026-11-14",
      "Days_To_Expiry": "60",
      "Contact_Status": "ติดต่อแล้ว-สนใจเปรียบเทียบ",
      "Historical_Renewal_Behavior": "ต่ออายุเฉียดฉิว",
      "premium": 8145,
      "daysToExpiryRaw": 60,
      "carYear": 2023
    },
    {
      "Customer_ID": "CUST-0096",
      "Customer_Name": "คุณลูกค้า 96",
      "Phone_Number": "0860-673-6560",
      "Car_Brand": "BYD",
      "Car_Model": "Atto 3",
      "Car_Year": "2023",
      "Current_Insurer": "บริษัท B (Safety Plus)",
      "Current_Policy_Type": "ชั้น 1",
      "Current_Premium_THB": "฿21,316",
      "Policy_Expiry_Date": "2026-10-06",
      "Days_To_Expiry": "21",
      "Contact_Status": "ยังไม่ได้ติดต่อ",
      "Historical_Renewal_Behavior": "ต่ออายุเฉียดฉิว",
      "premium": 21316,
      "daysToExpiryRaw": 21,
      "carYear": 2023
    },
    {
      "Customer_ID": "CUST-0097",
      "Customer_Name": "คุณลูกค้า 97",
      "Phone_Number": "0877-886-9915",
      "Car_Brand": "BYD",
      "Car_Model": "Dolphin",
      "Car_Year": "2023",
      "Current_Insurer": "บริษัท A (ANC Shield)",
      "Current_Policy_Type": "ชั้น 2+",
      "Current_Premium_THB": "฿12,154",
      "Policy_Expiry_Date": "2026-09-29",
      "Days_To_Expiry": "14",
      "Contact_Status": "ติดต่อแล้ว-ขอส่วนลด",
      "Historical_Renewal_Behavior": "ต่ออายุเฉียดฉิว",
      "premium": 12154,
      "daysToExpiryRaw": 14,
      "carYear": 2023
    },
    {
      "Customer_ID": "CUST-0098",
      "Customer_Name": "คุณลูกค้า 98",
      "Phone_Number": "0846-993-5234",
      "Car_Brand": "BMW",
      "Car_Model": "330e",
      "Car_Year": "2021",
      "Current_Insurer": "บริษัท D (Premium Care)",
      "Current_Policy_Type": "ชั้น 1",
      "Current_Premium_THB": "฿42,594",
      "Policy_Expiry_Date": "2026-09-18",
      "Days_To_Expiry": "3",
      "Contact_Status": "ยังไม่ได้ติดต่อ",
      "Historical_Renewal_Behavior": "ต่ออายุเฉียดฉิว",
      "premium": 42594,
      "daysToExpiryRaw": 3,
      "carYear": 2021
    },
    {
      "Customer_ID": "CUST-0099",
      "Customer_Name": "คุณลูกค้า 99",
      "Phone_Number": "0814-749-3219",
      "Car_Brand": "BMW",
      "Car_Model": "X3",
      "Car_Year": "2020",
      "Current_Insurer": "บริษัท B (Safety Plus)",
      "Current_Policy_Type": "ชั้น 1",
      "Current_Premium_THB": "฿29,619",
      "Policy_Expiry_Date": "2026-09-22",
      "Days_To_Expiry": "7",
      "Contact_Status": "ติดต่อแล้ว-ขอส่วนลด",
      "Historical_Renewal_Behavior": "ต่ออายุตรงเวลาเสมอ",
      "premium": 29619,
      "daysToExpiryRaw": 7,
      "carYear": 2020
    },
    {
      "Customer_ID": "CUST-0100",
      "Customer_Name": "คุณลูกค้า 100",
      "Phone_Number": "0818-649-4490",
      "Car_Brand": "Mercedes-Benz",
      "Car_Model": "C220d",
      "Car_Year": "2020",
      "Current_Insurer": "บริษัท A (ANC Shield)",
      "Current_Policy_Type": "ชั้น 2+",
      "Current_Premium_THB": "฿40,219",
      "Policy_Expiry_Date": "2026-10-30",
      "Days_To_Expiry": "45",
      "Contact_Status": "ยังไม่ได้ติดต่อ",
      "Historical_Renewal_Behavior": "เคยมีประวัติเคลมหนัก",
      "premium": 40219,
      "daysToExpiryRaw": 45,
      "carYear": 2020
    }
  ],
  "insurers": [
    {
      "Insurer_Code": "A",
      "Insurer_Name": "บริษัท A (ANC Shield)",
      "Allowed_Policy_Types": "ชั้น 1, ชั้น 2+, ชั้น 3+",
      "Max_Car_Age_Years": 10.0,
      "Allowed_Car_Brands": "Toyota, Honda, Mazda, Isuzu, Nissan",
      "Allowed_Car_Models": "ทุกรุ่นภายใต้ยี่ห้อที่อนุญาต (ไม่จำกัดเฉพาะบางรุ่น)",
      "Model_List_Scope": "Brand-level (รุ่นทั้งหมดในยี่ห้อผ่านหมด)",
      "Excluded_Car_Models": "-",
      "Min_Premium_THB": 8000.0,
      "Min_Premium_Basis": "เบี้ยขั้นต่ำของแผนใหม่ที่บริษัทนี้เสนอ",
      "Special_Conditions": "-",
      "maxAge": 10,
      "minPremium": 8000,
      "types": [
        "ชั้น 1",
        "ชั้น 2+",
        "ชั้น 3+"
      ],
      "brands": [
        "Toyota",
        "Honda",
        "Mazda",
        "Isuzu",
        "Nissan"
      ],
      "models": [],
      "excluded": "-"
    },
    {
      "Insurer_Code": "B",
      "Insurer_Name": "บริษัท B (Safety Plus)",
      "Allowed_Policy_Types": "ชั้น 1, ชั้น 2+",
      "Max_Car_Age_Years": 10.0,
      "Allowed_Car_Brands": "Toyota, Honda, Mazda, Isuzu, Nissan",
      "Allowed_Car_Models": "ทุกรุ่นภายใต้ยี่ห้อที่อนุญาต (ไม่จำกัดเฉพาะบางรุ่น)",
      "Model_List_Scope": "Brand-level (รุ่นทั้งหมดในยี่ห้อผ่านหมด)",
      "Excluded_Car_Models": "รถยนต์ไฟฟ้า (EV) ทุกยี่ห้อ/ทุกรุ่น",
      "Min_Premium_THB": 9000.0,
      "Min_Premium_Basis": "เบี้ยขั้นต่ำของแผนใหม่ที่บริษัทนี้เสนอ",
      "Special_Conditions": "-",
      "maxAge": 10,
      "minPremium": 9000,
      "types": [
        "ชั้น 1",
        "ชั้น 2+"
      ],
      "brands": [
        "Toyota",
        "Honda",
        "Mazda",
        "Isuzu",
        "Nissan"
      ],
      "models": [],
      "excluded": "รถยนต์ไฟฟ้า (EV) ทุกยี่ห้อ/ทุกรุ่น"
    },
    {
      "Insurer_Code": "C",
      "Insurer_Name": "บริษัท C (Thai Auto)",
      "Allowed_Policy_Types": "ชั้น 2+, ชั้น 3+",
      "Max_Car_Age_Years": 12.0,
      "Allowed_Car_Brands": "Toyota, Honda, Mazda, Isuzu, Nissan, BMW, Mercedes-Benz",
      "Allowed_Car_Models": "ทุกรุ่นภายใต้ยี่ห้อที่อนุญาต (ไม่จำกัดเฉพาะบางรุ่น)",
      "Model_List_Scope": "Brand-level (รุ่นทั้งหมดในยี่ห้อผ่านหมด)",
      "Excluded_Car_Models": "-",
      "Min_Premium_THB": 7000.0,
      "Min_Premium_Basis": "เบี้ยขั้นต่ำของแผนใหม่ที่บริษัทนี้เสนอ",
      "Special_Conditions": "ไม่มีเงื่อนไขอายุรถอื่นนอกจาก Max_Car_Age_Years",
      "maxAge": 12,
      "minPremium": 7000,
      "types": [
        "ชั้น 2+",
        "ชั้น 3+"
      ],
      "brands": [
        "Toyota",
        "Honda",
        "Mazda",
        "Isuzu",
        "Nissan",
        "BMW",
        "Mercedes-Benz"
      ],
      "models": [],
      "excluded": "-"
    },
    {
      "Insurer_Code": "D",
      "Insurer_Name": "บริษัท D (Premium Care)",
      "Allowed_Policy_Types": "ชั้น 1",
      "Max_Car_Age_Years": 8.0,
      "Allowed_Car_Brands": "Toyota, Honda, Mazda, BMW, Mercedes-Benz",
      "Allowed_Car_Models": "ทุกรุ่นภายใต้ยี่ห้อที่อนุญาต (ไม่จำกัดเฉพาะบางรุ่น)",
      "Model_List_Scope": "Brand-level (รุ่นทั้งหมดในยี่ห้อผ่านหมด)",
      "Excluded_Car_Models": "-",
      "Min_Premium_THB": 15000.0,
      "Min_Premium_Basis": "เบี้ยขั้นต่ำของแผนใหม่ที่บริษัทนี้เสนอ",
      "Special_Conditions": "-",
      "maxAge": 8,
      "minPremium": 15000,
      "types": [
        "ชั้น 1"
      ],
      "brands": [
        "Toyota",
        "Honda",
        "Mazda",
        "BMW",
        "Mercedes-Benz"
      ],
      "models": [],
      "excluded": "-"
    },
    {
      "Insurer_Code": "E",
      "Insurer_Name": "บริษัท E (Eco Guard)",
      "Allowed_Policy_Types": "ชั้น 2+, ชั้น 3+",
      "Max_Car_Age_Years": 5.0,
      "Allowed_Car_Brands": "Tesla, BYD, MG",
      "Allowed_Car_Models": "Model 3, Model Y, Atto 3, Dolphin, 4 EV, ZS",
      "Model_List_Scope": "Model-level (เฉพาะรุ่นที่ระบุเท่านั้น แม้ยี่ห้อจะผ่าน)",
      "Excluded_Car_Models": "-",
      "Min_Premium_THB": 6000.0,
      "Min_Premium_Basis": "เบี้ยขั้นต่ำของแผนใหม่ที่บริษัทนี้เสนอ",
      "Special_Conditions": "รับเฉพาะรถยนต์ไฟฟ้า (EV) เท่านั้น",
      "maxAge": 5,
      "minPremium": 6000,
      "types": [
        "ชั้น 2+",
        "ชั้น 3+"
      ],
      "brands": [
        "Tesla",
        "BYD",
        "MG"
      ],
      "models": [
        "Model 3",
        "Model Y",
        "Atto 3",
        "Dolphin",
        "4 EV",
        "ZS"
      ],
      "excluded": "-"
    }
  ]
};
